### ISSUE TITLE
Look into using Firebase in oncokb-curation

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb-transcript#106]
We want to use Firebase in our new curation platform as well.

```[tasklist]
### Tasks
- [x] How to use Firebase in react
- [x] Support real-time editing
- [x] How to track history, so we can revert back to previous data
- [x] Firebase db rules and authentication
```

**Comment by calvinlu3** [comment]
Here are two packages that look promising:

reactfire: https://github.com/FirebaseExtended/reactfire

react-firebase-hooks: https://github.com/CSFrequency/react-firebase-hooks

**Comment by calvinlu3** [comment]
There is no package to help handle the history of the database, so we need to manually write some functions to keep track of changes.
